openapi: 3.0.0
info:
  title: UniManager API Documentation
  description: Needs no description.
  version: 0.0.1
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
          example: Tina
        middle_name:
          type: string
          nullable: true
          example: Latoya
        last_name:
          type: string
          example: Turner
        email:
          type: string
          format: email
          example: tinaturner@example.com
        email_verified_at:
          type: string
          format: date-time
          nullable: true
        remember_token:
          type: string
          nullable: true
        password:
          type: string
          format: password
        phone:
          type: string
        address_line_1:
          type: string
        address_line_2:
          type: string
          nullable: true
        city:
          type: string
          example: Charlotte
        region:
          type: string
          example: North Carolina
        country:
          type: string
          example: United States of America
        postal_code:
          type: string
          example: 28001
        id_card:
          type: string
    UserRequestBody:
      type: object
      properties:
        first_name:
          type: string
          example: Tina
        middle_name:
          type: string
          nullable: true
          example: Latoya
        last_name:
          type: string
          example: Turner
        phone:
          type: string
        address_line_1:
          type: string
        address_line_2:
          type: string
          nullable: true
        city:
          type: string
          example: Charlotte
        region:
          type: string
          example: North Carolina
        country:
          type: string
          example: United States of America
        postal_code:
          type: string
          example: 28001
        id_card:
          type: string
    Department:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: DCIC
    DepartmentArray:
      type: array
      items:
        $ref: '#/components/schemas/Department'
    Major:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Computer Science
        department_id:
          type: integer
          format: int64
    MajorArray:
      type: array
      items:
        $ref: '#/components/schemas/Major'
    JobOffer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        requirements:
          type: string
        benefits:
          type: string
        interview_at:
          type: string
          format: date-time
        department_id:
          type: integer
          format: int64
        starts_at:
          type: string
          format: date-time
        ends_at:
          type: string
          format: date-time
        public:
          type: boolean
        department:
          $ref: '#/components/schemas/Department'
    JobOfferArray:
      type: array
      items:
        $ref: '#/components/schemas/JobOffer'
    ScholarshipOffer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        requirements:
          type: string
        starts_at:
          type: string
          format: date-time
        ends_at:
          type: string
          format: date-time
        public:
          type: boolean
        majors:
          type: array
          items:
            $ref: '#/components/schemas/Major'
          uniqueItems: true
    ScholarshipOfferArray:
      type: array
      items:
        $ref: '#/components/schemas/ScholarshipOffer'
    Application:
      type: object
      properties:
        id:
          type: integer
          format: int64
        number:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        user:
          $ref: '#/components/schemas/User'
        offer_id:
          type: integer
          format: int64
        offer_type:
          type: string
        status:
          type: string
        offer:
          type: object
          oneOf:
            - $ref: '#/components/schemas/JobOffer'
            - $ref: '#/components/schemas/ScholarshipOffer'
        major_id:
          type: integer
          format: int64
          nullable: true
        major:
          $ref: '#/components/schemas/Major'
        document_files:
          type: array
          items:
            $ref: '#/components/schemas/DocumentationFile'
          uniqueItems: true
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
          uniqueItems: true
    ApplicationArray:
      type: array
      items:
        $ref: '#/components/schemas/Application'
    DocumentationFile:
      type: object
      properties:
        id:
          type: integer
          format: int64
        path:
          type: string
          format: uri
        application_id:
          type: integer
          format: int64
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
          format: uri
        application_id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        user:
          $ref: '#/components/schemas/User'
    PaginatedLink:
      type: object
      properties:
        url:
          type: string
          nullable: true
          example: https://unimanager.snowlinks.net/api/model?page=5
        label:
          type: string
          example: 5
        active:
          type: boolean
  responses:
    OK:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: The action was performed successfully.
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: The page was not found.
    UnprocessableContent:
      description: Unprocessable Content
      content:
        application/json:
          schema:
            type: object
            properties:
              response:
                type: object
                properties:
                  status:
                    type: integer
                    minimum: 422
                    maximum: 422
                    example: 422
                  data:
                    type: object
                    properties:
                      errors:
                        type: object
                        additionalProperties:
                          type: array
                          items:
                            type: string
                      message:
                        type: string
                        example: The email field is required.
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: You do not have access rights to perform this action.
    CSRF:
      description: CSRF Mismatch
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: CSRF Mismatch
    User:
      description: User Response
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: integer
                format: int64
              first_name:
                type: string
                example: Tina
              middle_name:
                type: string
                nullable: true
                example: Latoya
              last_name:
                type: string
                example: Turner
              email:
                type: string
                format: email
                example: tinaturner@example.com
              phone:
                type: string
              address_line_1:
                type: string
              address_line_2:
                type: string
                nullable: true
              city:
                type: string
                example: Charlotte
              region:
                type: string
                example: North Carolina
              country:
                type: string
                example: United States of America
              postal_code:
                type: string
                example: 28001
              id_card:
                type: string
    DepartmentList:
      description: OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DepartmentArray'
    JobOfferPaginated:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/JobOfferArray'
              links:
                type: array
                items:
                  $ref: '#/components/schemas/PaginatedLink'
              current_page:
                type: integer
                example: 5
              per_page:
                type: integer
                example: 15
                default: 15
              from:
                type: integer
                example: 1
                nullable: true
              to:
                type: integer
                example: 15
                nullable: true
              total:
                type: integer
                example: 64
    ScholarshipOfferPaginated:
      description: OK
      content:
        application/json:
          schema:
            type: object
            properties:
              data:
                $ref: '#/components/schemas/ScholarshipOfferArray'
              links:
                type: array
                items:
                  $ref: '#/components/schemas/PaginatedLink'
              current_page:
                type: integer
                example: 5
              per_page:
                type: integer
                example: 15
                default: 15
              from:
                type: integer
                example: 1
                nullable: true
              to:
                type: integer
                example: 15
                nullable: true
              total:
                type: integer
                example: 64
  parameters:
    DepartmentId:
      in: path
      name: departmentId
      schema:
        type: integer
        format: int64
      required: true
      description: Numeric ID of the Department
    MajorId:
      in: path
      name: majorId
      schema:
        type: integer
        format: int64
      required: true
      description: Numeric ID of the Major
paths:
  /api/account:
    get:
      tags:
        - Users
      summary: Show account information.
      operationId: account.index
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '403':
          $ref: '#/components/responses/Forbidden'
        '419':
          $ref: '#/components/responses/CSRF'
  /api/account/update:
    patch:
      tags:
        - Users
      summary: Update account information.
      operationId: account.update
      requestBody:
        description: The updated data to save.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/User'
        '403':
          $ref: '#/components/responses/Forbidden'
        '419':
          $ref: '#/components/responses/CSRF'
        '422':
          $ref: '#/components/responses/UnprocessableContent'
  /api/departments:
    get:
      tags:
        - Departments
      summary: List all departments.
      operationId: departments.index
      responses:
        '200':
          $ref: '#/components/responses/DepartmentList'
        '403':
          $ref: '#/components/responses/Forbidden'
        '419':
          $ref: '#/components/responses/CSRF'
  /api/departments/store:
    post:
      tags:
        - Departments
      summary: Creates a new Department.
      operationId: departments.store
      requestBody:
        description: The new department's name.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '403':
          $ref: '#/components/responses/Forbidden'
        '419':
          $ref: '#/components/responses/CSRF'
        '422':
          $ref: '#/components/responses/UnprocessableContent'
  /api/departments/{departmentId}/find:
    get:
      tags:
        - Departments
      summary: Get a Department by ID
      operationId: departments.find
      parameters:
        - $ref: '#/components/parameters/DepartmentId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Department'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '419':
          $ref: '#/components/responses/CSRF'
  /api/departments/{departmentId}/update:
    patch:
      tags:
        - Departments
      summary: Update the identified Department.
      operationId: departments.update
      parameters:
        - $ref: '#/components/parameters/DepartmentId'
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '419':
          $ref: '#/components/responses/CSRF'
        '422':
          $ref: '#/components/responses/UnprocessableContent'
  /api/departments/{departmentId}/delete:
    delete:
      tags:
        - Departments
      summary: Delete the identified Department.
      operationId: departments.delete
      parameters:
        - $ref: '#/components/parameters/DepartmentId'
      responses:
        '200':
          $ref: '#/components/responses/OK'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '419':
          $ref: '#/components/responses/CSRF'
        '422':
          $ref: '#/components/responses/UnprocessableContent'
#
# TODO: add majors!
#
# TODO: add offers/job (all) here
  /api/offers/job/paginated:
    get:
      tags:
        - Job Offers
      summary: List all job offers in a paginated manner.
      operationId: offers.job.paginated
      responses:
        '200':
          $ref: '#/components/responses/JobOfferPaginated'
        '403':
          $ref: '#/components/responses/Forbidden'
        '419':
          $ref: '#/components/responses/CSRF'
# TODO: add the rest for offers/job here